### ISSUE TITLE
Exception when trying to call a method through tag of workflow

### ISSUE THREAD

**Issue by Ouriel** [infiniticio/infinitic#139]
I'm trying to call a method of a workflow by tag in a client:
```kotlin
infiniticClient.getWorkflowByTag(WorkflowImpl::class.java, tag = "My TAG").doSomething(metadata)
```
the workflow interface:
```kotlin
/** Journey workflow interface for stub purpose in client of infinitic and internal denomination */
interface WorkflowImpl {
  fun start(metadata: Metadata)

  fun doSomething(metadata: Metadata)
}
```
When running the code I get an exception:
```
java.lang.reflect.UndeclaredThrowableException
	at jdk.proxy2/jdk.proxy2.$Proxy27.doSomething(Unknown Source)
	at com.splio.journey.dispatcher.WorkflowManager.cancelWorkflows-IoAF18A(WorkflowManager.kt:44)
	at com.splio.journey.dispatcher.Dispatcher.handleUpdateJourney(Dispatcher.kt:84)
	at com.splio.journey.dispatcher.Dispatcher.access$handleUpdateJourney(Dispatcher.kt:34)
	at com.splio.journey.dispatcher.Dispatcher$special$$inlined$timer$1.run(Timer.kt:154)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: java.lang.Exception
	at io.infinitic.client.deferred.DeferredMethod.<init>(DeferredMethod.kt:71)
	at io.infinitic.client.deferred.DeferredMethod.<init>(DeferredMethod.kt)
	at io.infinitic.client.dispatcher.ClientDispatcherImpl.deferredMethod-pjI962M(ClientDispatcherImpl.kt:694)
	at io.infinitic.client.dispatcher.ClientDispatcherImpl.dispatchMethodAndWait(ClientDispatcherImpl.kt:659)
	at io.infinitic.client.dispatcher.ClientDispatcherImpl.dispatchAndWait(ClientDispatcherImpl.kt:147)
	at io.infinitic.common.proxies.ProxyHandler.invoke(ProxyHandler.kt:162)
	... 7 more
```

**Comment by Ouriel** [comment]
I also tried: 
```kotlin
 runCatching {
        infiniticClient.getWorkflowByTag(WorkflowImpl::class.java, tag = "My TAG")
      }
      .mapCatching { wkfTag -> infiniticClient.dispatch(wkfTag:: doSomething, metadata) }
 ```
 Got another Exception:
 ```
 java.lang.Exception
	at io.infinitic.client.deferred.DeferredMethod.<init>(DeferredMethod.kt:71)
	at io.infinitic.client.deferred.DeferredMethod.<init>(DeferredMethod.kt)
	at io.infinitic.client.dispatcher.ClientDispatcherImpl.deferredMethod-pjI962M(ClientDispatcherImpl.kt:694)
	at io.infinitic.client.dispatcher.ClientDispatcherImpl.dispatchMethodAsync(ClientDispatcherImpl.kt:636)
	at io.infinitic.client.dispatcher.ClientDispatcherImpl.dispatchAsync(ClientDispatcherImpl.kt:139)
	at io.infinitic.client.InfiniticClient.startAsync(InfiniticClient.kt:835)
	at io.infinitic.client.InfiniticClient.dispatchAsync(InfiniticClient.kt:232)
	at io.infinitic.client.InfiniticClient.dispatch(InfiniticClient.kt:347)
	at com.splio.journey.dispatcher.WorkflowManager.cancelWorkflows-IoAF18A(WorkflowManager.kt:44)
	at com.splio.journey.dispatcher.Dispatcher.handleUpdateJourney(Dispatcher.kt:84)
	at com.splio.journey.dispatcher.Dispatcher.access$handleUpdateJourney(Dispatcher.kt:34)
	at com.splio.journey.dispatcher.Dispatcher$special$$inlined$timer$1.run(Timer.kt:154)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
```
