### ISSUE TITLE
Error topic not found for namer on redeployment of Workflow Engine

### ISSUE THREAD

**Issue by Ouriel** [infiniticio/infinitic#148]
While upgrading the workflow engine in a rolling upgrade (3 pod(instances) of the workflow Engine running)
The app didn't start with an error of topic not found, the engine was deployed in the same namespace and the topic was existing.
The logs:
```
WARN  [id: 0x2b835240, L:/172.28.207.92:34972 - R:XXXXX] Received error from server: Topic Not Found.
ERROR [persistent://tenant-01/common/global-namer-partition-0] [null] Failed to create producer: {"errorMsg":"Topic Not Found.","reqId":1779783760430207949, "remote":"XXXXX", "local":"XXXXX"}
ERROR [persistent://tenant-01/common/global-namer] Could not create partitioned producer. 
```
Then app is crashing with this:
```
java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException$TopicDoesNotExistException: {"errorMsg":"Topic Not Found.","reqId":78035333971165745, "remote":"XXXXX", "local":"XXXXX"}
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
	at io.infinitic.pulsar.PulsarInfiniticWorker.start(PulsarInfiniticWorker.kt:138)
	at com.splio.journey.workflow.engine.AppKt.main(App.kt:24)
	at com.splio.journey.workflow.engine.AppKt.main(App.kt)
Caused by: org.apache.pulsar.client.api.PulsarClientException$TopicDoesNotExistException: {"errorMsg":"Topic Not Found.","reqId":78035333971165745,  "remote":"XXXXX", "local":"XXXXX"}
	at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:1066)
	at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:91)
	at io.infinitic.pulsar.GetProducerNameKt.getProducerName(getProducerName.kt:50)
	at io.infinitic.pulsar.PulsarInfiniticWorker$name$2.invoke(PulsarInfiniticWorker.kt:122)
	at io.infinitic.pulsar.PulsarInfiniticWorker$name$2.invoke(PulsarInfiniticWorker.kt:121)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.infinitic.pulsar.PulsarInfiniticWorker.getName(PulsarInfiniticWorker.kt:121)
	at io.infinitic.pulsar.PulsarInfiniticWorker$workerStarter$2.invoke(PulsarInfiniticWorker.kt:128)
	at io.infinitic.pulsar.PulsarInfiniticWorker$workerStarter$2.invoke(PulsarInfiniticWorker.kt:127)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.infinitic.pulsar.PulsarInfiniticWorker.getWorkerStarter(PulsarInfiniticWorker.kt:127)
	at io.infinitic.pulsar.PulsarInfiniticWorker.getWorkerStarter(PulsarInfiniticWorker.kt:55)
	at io.infinitic.workers.InfiniticWorker$startAsync$1.invokeSuspend(InfiniticWorker.kt:110)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException$TopicDoesNotExistException: {"errorMsg":"Topic Not Found.","reqId":78035333971165745,  "remote":"XXXXX", "local":"XXXXX"}
		at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
		at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118)
		at io.infinitic.workers.InfiniticWorker.start(InfiniticWorker.kt:89)
		at io.infinitic.pulsar.PulsarInfiniticWorker$startAsync$2.invokeSuspend(PulsarInfiniticWorker.kt:162)
		... 5 more
	Caused by: [CIRCULAR REFERENCE: org.apache.pulsar.client.api.PulsarClientException$TopicDoesNotExistException: {"errorMsg":"Topic Not Found.","reqId":78035333971165745, "remote":"XXXXX", "local":"XXXXX"}]
	```

**Comment by Ouriel** [comment]
It should be fixed by release 0.9.4 which change the topic to non-partitionned
